<a href="https://colab.research.google.com/github/jnsbrdbr/mlproject/blob/master/car_price%20_prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [123]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [124]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [125]:
data= pd.read_csv('/content/drive/MyDrive/ex01/USA_cars_datasets[1].csv')

In [126]:
data

,Unnamed: 0,price,brand,model,year,title_status,mileage,color,vin,lot,state,country,condition
0,0,6300,toyota,cruiser,2008,clean vehicle,274117.0,black,jtezu11f88k007763,159348797,new jersey,usa,10 days left
1,1,2899,ford,se,2011,clean vehicle,190552.0,silver,2fmdk3gc4bbb02217,166951262,tennessee,usa,6 days left
2,2,5350,dodge,mpv,2018,clean vehicle,39590.0,silver,3c4pdcgg5jt346413,167655728,georgia,usa,2 days left
3,3,25000,ford,door,2014,clean vehicle,64146.0,blue,1ftfw1et4efc23745,167753855,virginia,usa,22 hours left
4,4,27700,chevrolet,1500,2018,clean vehicle,6654.0,red,3gcpcrec2jg473991,167763266,florida,usa,22 hours left
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2494,2494,7800,nissan,versa,2019,clean vehicle,23609.0,red,3n1cn7ap9kl880319,167722715,california,usa,1 days left
2495,2495,9200,nissan,versa,2018,clean vehicle,34553.0,silver,3n1cn7ap5jl884088,167762225,florida,usa,21 hours left
2496,2496,9200,nissan,versa,2018,clean vehicle,31594.0,silver,3n1cn7ap9jl884191,167762226,florida,usa,21 hours left
2497,2497,9200,nissan,versa,2018,clean vehicle,32557.0,black,3n1cn7ap3jl883263,167762227,florida,usa,2 days left
2498,2498,9200,nissan,versa,2018,clean vehicle,31371.0,silver,3n1cn7ap4jl884311,167762228,florida,usa,21 hours left

In [127]:
print(data.columns)

Index(['Unnamed: 0', 'price', 'brand', 'model', 'year', 'title_status',
       'mileage', 'color', 'vin', 'lot', 'state', 'country', 'condition'],
      dtype='object')

In [128]:
df = data.drop('Unnamed: 0', axis=1)

In [129]:
df = df.drop('vin', axis=1)

In [130]:
df = df.drop('country', axis=1)

In [131]:
df

,price,brand,model,year,title_status,mileage,color,lot,state,condition
0,6300,toyota,cruiser,2008,clean vehicle,274117.0,black,159348797,new jersey,10 days left
1,2899,ford,se,2011,clean vehicle,190552.0,silver,166951262,tennessee,6 days left
2,5350,dodge,mpv,2018,clean vehicle,39590.0,silver,167655728,georgia,2 days left
3,25000,ford,door,2014,clean vehicle,64146.0,blue,167753855,virginia,22 hours left
4,27700,chevrolet,1500,2018,clean vehicle,6654.0,red,167763266,florida,22 hours left
...,...,...,...,...,...,...,...,...,...,...
2494,7800,nissan,versa,2019,clean vehicle,23609.0,red,167722715,california,1 days left
2495,9200,nissan,versa,2018,clean vehicle,34553.0,silver,167762225,florida,21 hours left
2496,9200,nissan,versa,2018,clean vehicle,31594.0,silver,167762226,florida,21 hours left
2497,9200,nissan,versa,2018,clean vehicle,32557.0,black,167762227,florida,2 days left
2498,9200,nissan,versa,2018,clean vehicle,31371.0,silver,167762228,florida,21 hours left

In [132]:
df['time_value']=df['condition'].str.split(' ').str[0]
df['time_obj']=df['condition'].str.split(' ').str[1]
df

,price,brand,model,year,title_status,mileage,color,lot,state,condition,time_value,time_obj
0,6300,toyota,cruiser,2008,clean vehicle,274117.0,black,159348797,new jersey,10 days left,10,days
1,2899,ford,se,2011,clean vehicle,190552.0,silver,166951262,tennessee,6 days left,6,days
2,5350,dodge,mpv,2018,clean vehicle,39590.0,silver,167655728,georgia,2 days left,2,days
3,25000,ford,door,2014,clean vehicle,64146.0,blue,167753855,virginia,22 hours left,22,hours
4,27700,chevrolet,1500,2018,clean vehicle,6654.0,red,167763266,florida,22 hours left,22,hours
...,...,...,...,...,...,...,...,...,...,...,...,...
2494,7800,nissan,versa,2019,clean vehicle,23609.0,red,167722715,california,1 days left,1,days
2495,9200,nissan,versa,2018,clean vehicle,34553.0,silver,167762225,florida,21 hours left,21,hours
2496,9200,nissan,versa,2018,clean vehicle,31594.0,silver,167762226,florida,21 hours left,21,hours
2497,9200,nissan,versa,2018,clean vehicle,32557.0,black,167762227,florida,2 days left,2,days
2498,9200,nissan,versa,2018,clean vehicle,31371.0,silver,167762228,florida,21 hours left,21,hours

In [133]:
df['time_value'].replace('Listing',0, inplace=True)

<ipython-input-133-b8f1cb4479b0>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['time_value'].replace('Listing',0, inplace=True)

In [134]:
df['time_obj'].value_counts()

time_obj
days       1395
hours      1030
minutes      54
Expired      20
Name: count, dtype: int64

In [135]:
df['time_value'].value_counts()

time_value
2     858
21    492
3     139
1     109
14    108
8      82
17     76
20     67
6      64
9      61
22     57
7      50
18     48
19     45
11     42
16     37
10     23
5      22
0      20
29     18
4      17
23     16
15     12
24      9
12      9
34      7
47      2
48      2
32      1
13      1
53      1
27      1
30      1
28      1
36      1
Name: count, dtype: int64

In [136]:
df['time_value'] = df['time_value'].astype(int)
df

,price,brand,model,year,title_status,mileage,color,lot,state,condition,time_value,time_obj
0,6300,toyota,cruiser,2008,clean vehicle,274117.0,black,159348797,new jersey,10 days left,10,days
1,2899,ford,se,2011,clean vehicle,190552.0,silver,166951262,tennessee,6 days left,6,days
2,5350,dodge,mpv,2018,clean vehicle,39590.0,silver,167655728,georgia,2 days left,2,days
3,25000,ford,door,2014,clean vehicle,64146.0,blue,167753855,virginia,22 hours left,22,hours
4,27700,chevrolet,1500,2018,clean vehicle,6654.0,red,167763266,florida,22 hours left,22,hours
...,...,...,...,...,...,...,...,...,...,...,...,...
2494,7800,nissan,versa,2019,clean vehicle,23609.0,red,167722715,california,1 days left,1,days
2495,9200,nissan,versa,2018,clean vehicle,34553.0,silver,167762225,florida,21 hours left,21,hours
2496,9200,nissan,versa,2018,clean vehicle,31594.0,silver,167762226,florida,21 hours left,21,hours
2497,9200,nissan,versa,2018,clean vehicle,32557.0,black,167762227,florida,2 days left,2,days
2498,9200,nissan,versa,2018,clean vehicle,31371.0,silver,167762228,florida,21 hours left,21,hours

In [137]:
conditions = [df['time_obj'] == 'days', df['time_obj'] == 'hours',
              df['time_obj'] == 'minutes', df['time_obj'] == 'Expired']
choicelist = [df['time_value']*24*60, df['time_value']*60,
              df['time_value']*1, df['time_value']*0]
df['minutes_left'] = np.select(conditions, choicelist)
df

,price,brand,model,year,title_status,mileage,color,lot,state,condition,time_value,time_obj,minutes_left
0,6300,toyota,cruiser,2008,clean vehicle,274117.0,black,159348797,new jersey,10 days left,10,days,14400
1,2899,ford,se,2011,clean vehicle,190552.0,silver,166951262,tennessee,6 days left,6,days,8640
2,5350,dodge,mpv,2018,clean vehicle,39590.0,silver,167655728,georgia,2 days left,2,days,2880
3,25000,ford,door,2014,clean vehicle,64146.0,blue,167753855,virginia,22 hours left,22,hours,1320
4,27700,chevrolet,1500,2018,clean vehicle,6654.0,red,167763266,florida,22 hours left,22,hours,1320
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2494,7800,nissan,versa,2019,clean vehicle,23609.0,red,167722715,california,1 days left,1,days,1440
2495,9200,nissan,versa,2018,clean vehicle,34553.0,silver,167762225,florida,21 hours left,21,hours,1260
2496,9200,nissan,versa,2018,clean vehicle,31594.0,silver,167762226,florida,21 hours left,21,hours,1260
2497,9200,nissan,versa,2018,clean vehicle,32557.0,black,167762227,florida,2 days left,2,days,2880
2498,9200,nissan,versa,2018,clean vehicle,31371.0,silver,167762228,florida,21 hours left,21,hours,1260

In [138]:
df = df.drop('condition', axis=1)

In [139]:
df = df.drop('time_value', axis=1)

In [140]:
df = df.drop('time_obj', axis=1)

In [141]:
df

,price,brand,model,year,title_status,mileage,color,lot,state,minutes_left
0,6300,toyota,cruiser,2008,clean vehicle,274117.0,black,159348797,new jersey,14400
1,2899,ford,se,2011,clean vehicle,190552.0,silver,166951262,tennessee,8640
2,5350,dodge,mpv,2018,clean vehicle,39590.0,silver,167655728,georgia,2880
3,25000,ford,door,2014,clean vehicle,64146.0,blue,167753855,virginia,1320
4,27700,chevrolet,1500,2018,clean vehicle,6654.0,red,167763266,florida,1320
...,...,...,...,...,...,...,...,...,...,...
2494,7800,nissan,versa,2019,clean vehicle,23609.0,red,167722715,california,1440
2495,9200,nissan,versa,2018,clean vehicle,34553.0,silver,167762225,florida,1260
2496,9200,nissan,versa,2018,clean vehicle,31594.0,silver,167762226,florida,1260
2497,9200,nissan,versa,2018,clean vehicle,32557.0,black,167762227,florida,2880
2498,9200,nissan,versa,2018,clean vehicle,31371.0,silver,167762228,florida,1260

In [142]:
from sklearn.preprocessing import OrdinalEncoder
enc = OrdinalEncoder()
data_num = df.iloc[:, [0, 3, 5, 7, 9]]
data_num = data_num.astype(int)
data_num

      price  year  mileage        lot  minutes_left
0      6300  2008   274117  159348797         14400
1      2899  2011   190552  166951262          8640
2      5350  2018    39590  167655728          2880
3     25000  2014    64146  167753855          1320
4     27700  2018     6654  167763266          1320
...     ...   ...      ...        ...           ...
2494   7800  2019    23609  167722715          1440
2495   9200  2018    34553  167762225          1260
2496   9200  2018    31594  167762226          1260
2497   9200  2018    32557  167762227          2880
2498   9200  2018    31371  167762228          1260

[2499 rows x 5 columns]

In [143]:
data_cat = df.iloc[:, [1, 2, 4, 6, 8]]
data_cat

          brand    model   title_status   color       state
0        toyota  cruiser  clean vehicle   black  new jersey
1          ford       se  clean vehicle  silver   tennessee
2         dodge      mpv  clean vehicle  silver     georgia
3          ford     door  clean vehicle    blue    virginia
4     chevrolet     1500  clean vehicle     red     florida
...         ...      ...            ...     ...         ...
2494     nissan    versa  clean vehicle     red  california
2495     nissan    versa  clean vehicle  silver     florida
2496     nissan    versa  clean vehicle  silver     florida
2497     nissan    versa  clean vehicle   black     florida
2498     nissan    versa  clean vehicle  silver     florida

[2499 rows x 5 columns]

In [144]:
enc.fit(data_cat)
data_cat_to_num = enc.transform(data_cat)
data_cat_to_num

array([[ 27.,  25.,   0.,   2.,  24.],
       [  8.,  92.,   0.,  39.,  35.],
       [  7.,  75.,   0.,  39.,   7.],
       ...,
       [ 24., 120.,   0.,  39.,   6.],
       [ 24., 120.,   0.,   2.,   6.],
       [ 24., 120.,   0.,  39.,   6.]])

In [145]:
data_cat_to_num_frame = pd.DataFrame(data_cat_to_num)
data_cat_to_num_frame

         0      1    2     3     4
0     27.0   25.0  0.0   2.0  24.0
1      8.0   92.0  0.0  39.0  35.0
2      7.0   75.0  0.0  39.0   7.0
3      8.0   32.0  0.0   4.0  39.0
4      5.0    0.0  0.0  34.0   6.0
...    ...    ...  ...   ...   ...
2494  24.0  120.0  0.0  34.0   3.0
2495  24.0  120.0  0.0  39.0   6.0
2496  24.0  120.0  0.0  39.0   6.0
2497  24.0  120.0  0.0   2.0   6.0
2498  24.0  120.0  0.0  39.0   6.0

[2499 rows x 5 columns]

In [146]:
data_cat_to_num_frame.rename(columns={0:'brand', 1:'model', 2:'status', 3:'color', 4:'state'},
                             inplace=True)
data_cat_to_num_frame

      brand  model  status  color  state
0      27.0   25.0     0.0    2.0   24.0
1       8.0   92.0     0.0   39.0   35.0
2       7.0   75.0     0.0   39.0    7.0
3       8.0   32.0     0.0    4.0   39.0
4       5.0    0.0     0.0   34.0    6.0
...     ...    ...     ...    ...    ...
2494   24.0  120.0     0.0   34.0    3.0
2495   24.0  120.0     0.0   39.0    6.0
2496   24.0  120.0     0.0   39.0    6.0
2497   24.0  120.0     0.0    2.0    6.0
2498   24.0  120.0     0.0   39.0    6.0

[2499 rows x 5 columns]

In [147]:
df = pd.concat([data_num, data_cat_to_num_frame], axis=1)
df

,price,year,mileage,lot,minutes_left,brand,model,status,color,state
0,6300,2008,274117,159348797,14400,27.0,25.0,0.0,2.0,24.0
1,2899,2011,190552,166951262,8640,8.0,92.0,0.0,39.0,35.0
2,5350,2018,39590,167655728,2880,7.0,75.0,0.0,39.0,7.0
3,25000,2014,64146,167753855,1320,8.0,32.0,0.0,4.0,39.0
4,27700,2018,6654,167763266,1320,5.0,0.0,0.0,34.0,6.0
...,...,...,...,...,...,...,...,...,...,...
2494,7800,2019,23609,167722715,1440,24.0,120.0,0.0,34.0,3.0
2495,9200,2018,34553,167762225,1260,24.0,120.0,0.0,39.0,6.0
2496,9200,2018,31594,167762226,1260,24.0,120.0,0.0,39.0,6.0
2497,9200,2018,32557,167762227,2880,24.0,120.0,0.0,2.0,6.0
2498,9200,2018,31371,167762228,1260,24.0,120.0,0.0,39.0,6.0

In [148]:
# Randomly shuffle the data
data = df.sample(frac=1, random_state=42)

# Split based on fraction
test_frac = 0.2
test_size = int(len(data) * test_frac)

# Create test and train sets
test = data.iloc[:test_size].reset_index(drop=True)
train = data.iloc[test_size:].reset_index(drop=True)

In [149]:
X = train.iloc[:, 1:]
y = train['price']

In [150]:
y

0        5800
1       23100
2        8000
3           0
4       17100
        ...
1995    20000
1996    21000
1997    23300
1998    23200
1999    21500
Name: price, Length: 2000, dtype: int64

In [151]:
test

,price,year,mileage,lot,minutes_left,brand,model,status,color,state
0,11390,2015,37953,167654210,15840,24.0,33.0,0.0,40.0,26.0
1,27900,2019,28922,167801390,2880,8.0,49.0,0.0,15.0,6.0
2,2500,2013,163260,167532547,900,7.0,117.0,1.0,34.0,35.0
3,10900,2019,31037,167457191,2880,24.0,94.0,0.0,15.0,1.0
4,23600,2019,13466,167735027,1260,8.0,112.0,0.0,46.0,16.0
...,...,...,...,...,...,...,...,...,...,...
494,7600,2012,79544,167612530,1020,7.0,32.0,1.0,46.0,36.0
495,17150,2015,67091,167565081,12960,8.0,33.0,0.0,2.0,24.0
496,29000,2017,42291,167736241,1260,8.0,32.0,0.0,2.0,35.0
497,51000,2019,24869,167615142,840,8.0,72.0,0.0,34.0,17.0
498,25300,2019,17515,167750648,1260,7.0,15.0,0.0,34.0,25.0

In [152]:
import pandas as pd
from sklearn.pipeline import Pipeline
from sklearn.tree import DecisionTreeRegressor
from sklearn.model_selection import GridSearchCV, KFold, train_test_split
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score


# Optional: split train into training and validation
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, random_state=42)

# Define pipeline
pipeline = Pipeline([
    ('tree', DecisionTreeRegressor(random_state=42))
])

# Define hyperparameter grid
param_grid = {
    'tree__max_depth': [3, 5, 10, None],
    'tree__min_samples_split': [2, 5, 10],
    'tree__min_samples_leaf': [1, 2, 4],
    'tree__criterion': ['squared_error', 'absolute_error']
}

# KFold cross-validation
cv = KFold(n_splits=5, shuffle=True, random_state=42)

# Grid search with MSE scoring
grid_search = GridSearchCV(
    pipeline,
    param_grid,
    cv=cv,
    scoring='neg_mean_squared_error',
    n_jobs=-1
)

# Train the model on training data
grid_search.fit(X_train, y_train)

# Best model from grid search
best_model = grid_search.best_estimator_

# --------------------------
# ✅ Evaluation on validation set
# --------------------------
y_val_pred = best_model.predict(X_val)

print("----- Validation Set Evaluation -----")
print("Best hyperparameters:", grid_search.best_params_)
print("Validation MSE:", mean_squared_error(y_val, y_val_pred))
print("Validation MAE:", mean_absolute_error(y_val, y_val_pred))
print("Validation R² Score:", r2_score(y_val, y_val_pred))

# --------------------------
# ✅ Evaluation on test set (if ground truth is known)
# --------------------------

# Clean test set to match training features
test_clean = test[X.columns]

# If you have true labels for test set (e.g., in competitions with public test sets)
# Uncomment and use this block
y_test = test['price']
y_test_pred = best_model.predict(test_clean)
print("----- Test Set Evaluation -----")
print("Test MSE:", mean_squared_error(y_test, y_test_pred))
print("Test MAE:", mean_absolute_error(y_test, y_test_pred))
print("Test R² Score:", r2_score(y_test, y_test_pred))

# --------------------------
# ✅ Final prediction for submission (no ground truth available)
# --------------------------

test_pred = best_model.predict(test_clean)

----- Validation Set Evaluation -----
Best hyperparameters: {'tree__criterion': 'squared_error', 'tree__max_depth': 10, 'tree__min_samples_leaf': 4, 'tree__min_samples_split': 10}
Validation MSE: 69545697.03762972
Validation MAE: 5560.38115428737
Validation R² Score: 0.4669980088980026
----- Test Set Evaluation -----
Test MSE: 72955577.07752793
Test MAE: 5750.238028946927
Test R² Score: 0.5395347058480027